require("dotenv").config();
const expect = require("chai").expect;
const lectureController = require("../controllers/lecture");
const faker = require("faker");
const mongoose = require("mongoose");
const Lecture = require("../models/lecture");

describe("Lectures", function() {
  this.timeout(5000);
  before(async function() {
    await mongoose.connect(process.env.TEST_MONGODB_URI);
    const lecture = new Lecture({
      title: "Test Lecture",
      dayOfWeek: 3,
      start: "2019-06-10T12:00:00.894+00:00",
      end: "2019-06-10T16:00:00.894+00:00",
      capacity: 30
    });
    await lecture.save();
  });

  it("should fetch autogenerated lecture", async function() {
    const lecture = await Lecture.findOne();
    console.log(lecture);
  });

  after(async function() {
    await Lecture.deleteMany({});
    await mongoose.disconnect();
  });
});
